export const GET_ANSWERS = "GET_ANSWERS";
export const GET_ANSWER = "GET_ANSWER";
export const UPDATE_ANSWER = "UPDATE_ANSWER";
export const DELETE_ANSWER = "DELETE_ANSWER";
export const POST_ANSWER = "POST_ANSWER";
export const VOTE_ANSWER = "VOTE_ANSWER";
export const ANSWERS_LOADING = "ANSWERS_LOADING";
export const TOGGLE_PREFERRED = "TOGGLE_PREFERRED";




